// <auto-generated />
using System;
using AutoRecon.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AutoRecon.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260420173040_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.6");

            modelBuilder.Entity("AutoRecon.Models.Scan", b =>
                {
                    b.Property<int>("ScanID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("RawJSON")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("TargetID")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("TEXT");

                    b.HasKey("ScanID");

                    b.HasIndex("TargetID");

                    b.ToTable("Scans");
                });

            modelBuilder.Entity("AutoRecon.Models.Target", b =>
                {
                    b.Property<int>("TargetID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Hostname")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("IPAddress")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("UserID")
                        .HasColumnType("INTEGER");

                    b.HasKey("TargetID");

                    b.HasIndex("UserID");

                    b.ToTable("Targets");
                });

            modelBuilder.Entity("AutoRecon.Models.User", b =>
                {
                    b.Property<int>("UserID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("UserID");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("AutoRecon.Models.Vulnerability", b =>
                {
                    b.Property<int>("VulnID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AIDescription")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ScanID")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("VulnID");

                    b.HasIndex("ScanID");

                    b.ToTable("Vulnerabilities");
                });

            modelBuilder.Entity("AutoRecon.Models.Scan", b =>
                {
                    b.HasOne("AutoRecon.Models.Target", "Target")
                        .WithMany("Scans")
                        .HasForeignKey("TargetID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Target");
                });

            modelBuilder.Entity("AutoRecon.Models.Target", b =>
                {
                    b.HasOne("AutoRecon.Models.User", "User")
                        .WithMany("Targets")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("AutoRecon.Models.Vulnerability", b =>
                {
                    b.HasOne("AutoRecon.Models.Scan", "Scan")
                        .WithMany("Vulnerabilities")
                        .HasForeignKey("ScanID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Scan");
                });

            modelBuilder.Entity("AutoRecon.Models.Scan", b =>
                {
                    b.Navigation("Vulnerabilities");
                });

            modelBuilder.Entity("AutoRecon.Models.Target", b =>
                {
                    b.Navigation("Scans");
                });

            modelBuilder.Entity("AutoRecon.Models.User", b =>
                {
                    b.Navigation("Targets");
                });
#pragma warning restore 612, 618
        }
    }
}
